### ISSUE TITLE
Version check fails

### ISSUE THREAD

**Issue by cpm9** [AHilyard/AdvancementPlaques#11]
in server latest.log during startup the fml version checker fails and causes a warning log for both advancement plaques and iceberg

using mc 1.18.2
forge 40.1.20
plaques 1.4.3
iceberg 1.0.40

[17May2022 23:22:48.197] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [advancementplaques] Starting version check at https://mc-curse-update-checker.herokuapp.com/499826
[17May2022 23:22:48.965] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2319!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:175) ~[fmlcore-1.18.2-40.1.19.jar%23117!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.18.2-40.1.19.jar%23117!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2319!/:?]
	... 6 more

[17May2022 23:22:49.533] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2319!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:175) ~[fmlcore-1.18.2-40.1.19.jar%23117!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.18.2-40.1.19.jar%23117!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2319!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2319!/:?]
	... 6 more

**Comment by AHilyard** [comment]
Hi there, yes I discovered this issue yesterday and it is actually due to a problem with [ephys](https://github.com/ephys)/[mc-curseforge-updateJSONURL](https://github.com/ephys/mc-curseforge-updateJSONURL).  I've reached out to the developer for a resolution, but if I don't hear back I will be updating to another service for update checks.  I will update this issue when I know more.

**Comment by AHilyard** [comment]
I've updated Iceberg with a workaround that fixes update checking for all my mods.  Enjoy! 😄
