### ISSUE TITLE
[1.20.4] CRITICAL Minecraft crashes on initialize when trying to getColor()

### ISSUE THREAD

**Issue by cyberaspect** [AHilyard/AdvancementPlaques#34]
Title says most of it. This first happened when on a server and when I got Monster Hunter, the bright advancement toast faded in but before it showed anything it crashed and it hasn't been able to open since. I don't remember changing the settings of this mod with Mod Menu but maybe I did and now all this. Disabling the mod seems to clear up all the issues so it's not too severe, but I would like to have this mod just because it looks AWESOME.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-12-29 21:26:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'advancementplaques'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_5251 net.minecraft.class_5251.method_27719(java.lang.String)'
	at com.anthonyhilyard.advancementplaques.config.AdvancementPlaquesConfig.getColor(AdvancementPlaquesConfig.java:249)
	at com.anthonyhilyard.advancementplaques.config.AdvancementPlaquesConfig.validateColor(AdvancementPlaquesConfig.java:228)
	at com.anthonyhilyard.advancementplaques.config.AdvancementPlaquesConfig.lambda$new$0(AdvancementPlaquesConfig.java:90)
	at net.minecraftforge.common.ForgeConfigSpec$ValueSpec.test(ForgeConfigSpec.java:828)
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:224)
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:190)
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:190)
	at net.minecraftforge.common.ForgeConfigSpec.isCorrect(ForgeConfigSpec.java:133)
	at net.minecraftforge.common.ForgeConfigSpec.setConfig(ForgeConfigSpec.java:68)
	at net.minecraftforge.common.ForgeConfigSpec.acceptConfig(ForgeConfigSpec.java:89)
	at net.minecraftforge.fml.config.ModConfig.setConfigData(ModConfig.java:87)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:74)
	at net.minecraftforge.fml.config.ConfigTracker.trackConfig(ConfigTracker.java:57)
	at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:44)
	at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:51)
	at fuzs.forgeconfigapiport.impl.config.ForgeConfigRegistryV2Impl.register(ForgeConfigRegistryV2Impl.java:11)
	at com.anthonyhilyard.advancementplaques.AdvancementPlaques.onClientSetup(AdvancementPlaques.java:35)
	at com.anthonyhilyard.advancementplaques.Loader.onInitializeClient(Loader.java:18)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
```
thanks again :D

**Comment by AHilyard** [comment]
Thank you for the report, I have determined the issue and released a new version that should fix it.  You can find it here:
https://modrinth.com/mod/advancement-plaques/version/wDGTVjTo
or here:
https://legacy.curseforge.com/minecraft/mc-mods/advancement-plaques-fabric/files/4999940

Enjoy! 😄

**Comment by cyberaspect** [comment]
Thank you so much!
